CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('developer', 'tester')),
    created_at TEXT NOT NULL
);

CREATE TABLE password_resets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE login_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    email TEXT NOT NULL,
    ip_address TEXT NOT NULL,
    user_agent TEXT NOT NULL,
    logged_in_at TEXT NOT NULL
);

CREATE TABLE password_reset_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    administrator_email TEXT NOT NULL,
    target_email TEXT NOT NULL,
    reset_at TEXT NOT NULL
);

CREATE TABLE change_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_signal_id TEXT NOT NULL,
    function_name TEXT NOT NULL,
    previous_value TEXT NOT NULL DEFAULT '',
    new_value TEXT NOT NULL DEFAULT '',
    developer_name TEXT NOT NULL,
    developer_id BIGINT NOT NULL REFERENCES users(id),
    tester_name TEXT NOT NULL,
    tester_email TEXT NOT NULL,
    reason TEXT NOT NULL,
    priority TEXT NOT NULL CHECK (priority IN ('Low', 'Medium', 'High', 'Critical')),
    status TEXT NOT NULL DEFAULT 'New' CHECK (status IN ('New', 'In Review', 'Approved', 'Rejected')),
    notification_status TEXT NOT NULL DEFAULT 'Pending',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);